### ISSUE TITLE
There is some problems when count of fetched order data doesn't equal N["服务评价"]

### ISSUE THREAD

**Issue by haohongwei** [Dimlitter/jd_AutoComment#23]
In the second time of enumerate(req_et), i.xpath return nothing .
And the result of the Order_data will be null.
So it can not do any '服务评价' .

But I have not found why  i.xpath can not found any element in the second time.
So I delete the second enumerate(req_et) ,even thought the count is not same.
```
  for idx, i in enumerate(req_et):
        opts['logger'].info(i)
        opts['logger'].debug('Loop: %d / %d', idx + 1, loop_times)
        opts['logger'].debug('Fetching order data in the default XPath')
        elems = i.xpath(
            '//*[@id="main"]/div[2]/div[2]/table/tbody/tr[@class="tr-bd"]')
        opts['logger'].debug('Count of fetched order data: %d', len(elems))
        Order_data.extend(elems)
    if len(Order_data) != N['服务评价']:
        opts['logger'].debug(
            'Count of fetched order data doesn\'t equal N["服务评价"]')
        opts['logger'].debug('Clear the list Order_data')
        Order_data = []
        opts['logger'].debug('Total loop times: %d', loop_times)
        for idx, i in enumerate(req_et):
            opts['logger'].debug('Loop: %d / %d', idx + 1, loop_times)
            opts['logger'].debug('Fetching order data in another XPath')
            elems = i.xpath(
                '//*[@id="main"]/div[2]/div[2]/table/tr[@class="tr-bd"]')
            opts['logger'].debug('Count of fetched order data: %d', len(elems))
            Order_data.extend(elems)
```

**Comment by LittleYe233** [comment]
I think this situation happened because:

- your network was unstable and the JD server couldn't respond to the response from Python;
- the JD server detected this abnormal request and responded with an invalid webpage;
- JD had changed the way to generate the order elements of "服务评价" so that the XPaths couldn't find the targets

and so on. It's better to run this program with `--log-level DEBUG` to check if the problem still exists. If so, check if the count of fetched order data is zero or a number different from `N["服务评价"]` at the first time to execute `i.xpath()`.

> But I have not found why i.xpath can not found any element in the second time.

I think it's normal. The second `i.xpath()` statement is just a fallback because we have found only this one works for some certain users. For most users the first one is enough.
